alias Ppa.{PpaUniversitiesAssociation, Repo}
import Ecto.Query

confirmed = [["Academia de Varejo", 12],
["ACE - Faculdade Guilherme Guimbala", 248],
["AESPI - Associação de Ensino Superior do Piauí", 109],
["Anhanguera", 24],
["Associação Educacional Dom Bosco", 104],
["Castelli Escola Superior de Hotelaria", 300],
["Centro Universitário Celso Lisboa", 322],
["Centro Universitário IBMR", 1181],
["CENTRO UNIVERSITÁRIO METODISTA - IPA", 1308],
["Centro Universitário Módulo", 1316],
["Centro Universitário Unihorizontes", 1550],
["Cesrei Faculdade", 341],
["CESUFOZ -Centro de Ensino Superior de Foz do Iguaçu", 346],
["CESVASF - Centro de Ensino Superior do Vale do São Francisco", 2443],
["CESV - Centro de Ensino Superior de Vitória", 352],
["Cetep", 356],
["CEUNSP", 362],
["COESP – Centro Odontológico de Estudos e Pesquisas", 2185],
["Dom Alberto", 382],
["EAP - Espaço de Aperfeiçoamento Profissional", 1922],
["EESAP", 2775],
["EEWB – Escola de Enfermagem Wenceslau Braz", 395],
["ESAB - Escola Superior Aberta do Brasil", 401],
["ESBAM - Escola Superior Batista do Amazonas", 404],
["Estácio", 19],
["FAAG - Faculdade Agudos", 432],
["FAAHF - Faculdade Arnaldo Horário Ferreira", 433],
["FAAM - Faculdade da Amazônia", 435],
["FABAD - Faculdade Bíblica das Assembleias de Deus", 2165],
["FABEC - Faculdade Brasileira de Educação e Cultura", 444],
["FABEL - Faculdade de Belém", 447],
["FABEX - Faculdade Brasileira de Ensino Pesquisa e Extensão", 1743],
["FABIC – Faculdade do Bico do Papagaio", 452],
["FABRAN - Faculdade Brasil Norte", 2133],
["FACAB - Faculdade de Casa Branca", 454],
["FACAR - Faculdade de Aracaju", 1713],
["FACEM - Faculdade do Estado do Maranhão", 1564],
["FACEMG - Faculdade de Ensino de Minas Gerais", 1565],
["FACEN", 481],
["FACESF - Faculdade de Ciências Humanas do São Francisco", 494],
["FACESP", 2719],
["FACESP - Faculdade de Educação Superior de Pernambuco", 2239],
["FACESTA - Faculdade Católica São Tomás Aquino", 1993],
["FAC - Faculdade Curitibana", 2135],
["FACHA - Faculdades Integradas Hélio Alonso", 503],
["FACHASUL - Faculdade de Chapadão do Sul", 504],
["FACHO - Faculdade de Ciências Humanas de Olinda", 505],
["FACIG -  Faculdade de Ciências Gerenciais de Manhuaçu", 513],
["FACIG - Faculdade de Igarassu", 512],
["FACIMA - Faculdade da Cidade de Maceió", 2134],
["FACIMED -  Faculdade de Ciências Biomédicas de Cacoal", 516],
["FACITEN - Faculdade de Ciências e Tecnologia de Natal", 1938],
["FACMAIS - Faculdade de Inhumas", 530],
["FACPED – Faculdade Padre Dourado", 2786],
["FACSETE - Faculdade de Sete Lagoas", 2004],
["FACSUM - Faculdade do Sudeste Mineiro", 1567],
["FACTIVA - Faculdade de Tecnologia de Valença", 1988],
["Faculdade AIEC", 255],
["Faculdade Alfa", 2349],
["Faculdade Apogeu", 691],
["Faculdade Ari de Sá", 1970],
["Faculdade Arnaldo", 156],
["Faculdade Arthur Thomas", 440],
["Faculdade ASPER", 201],
["Faculdade Ateneu", 138],
["Faculdade Batista de Minas Gerais", 1412],
["Faculdade Boas Novas", 592],
["Faculdade Camões", 294],
["Faculdade Campos Elíseos", 8],
["Faculdade Campos Salles", 72],
["Faculdade Católica de Anápolis", 307],
["Faculdade Católica de Feira de Santana", 2803],
["Faculdade Católica de Fortaleza", 308],
["Faculdade Católica Paulista", 1828],
["Faculdade Catuaí", 598],
["Faculdade Cearense", 692],
["Faculdade Cerrado", 2665],
["FACULDADE CET", 354],
["Faculdade da Serra Gaúcha - Bento Gonçalves", 1114],
["Faculdade Decisão", 379],
["Faculdade Delta", 615],
["Faculdade de Negócios Metropolitana", 1310],
["Faculdade de São Lourenço", 686],
["Faculdade de Tecnologia Finaci", 1932],
["Faculdade de Tecnologia Senac DF", 553],
["Faculdade do Clube Náutico Mogiano", 1325],
["Faculdade do Futuro", 620],
["Faculdade Dom Luiz de Orleans e Bragança", 2358],
["Faculdade Dom Pedro II", 1980],
["Faculdade do Tapajós", 930],
["Faculdade Drummond", 9],
["Faculdade Duarte Coelho", 1834],
["Faculdade Eficaz", 1235],
["Faculdade Equipe", 126],
["Faculdade Esamc", 0],
["Faculdade Evolução", 1924],
["Faculdade Evolutivo", 488],
["Faculdade Fabra", 1905],
["Faculdade FACEM", 1564],
["Faculdade FADAM", 2747],
["Faculdade FAEL", 735],
["Faculdade Fasipe", 137],
["Faculdade FATEPI", 924],
["Fáculdade FGP", 1026],
["Faculdade Gaúcha", 2336],
["Faculdade Hélio Rocha", 1166],
["Faculdade Herrero", 1167],
["Faculdade Horizonte", 1802],
["Faculdade IDEAU", 1189],
["Faculdade IESA", 1197],
["Faculdade IESM", 1238],
["Faculdade Impacta", 20],
["Faculdade INCISOH", 1735],
["Faculdade Innovare", 1957],
["Faculdade Inspirar", 1233],
["Faculdade Ipanema", 644],
["Faculdade ISEO", 1258],
["Faculdade Jardins", 2001],
["Faculdade Joaquim Nabuco", 1284],
["Faculdade Lions", 528],
["Faculdade LS", 1292],
["Faculdade Madre Tereza", 1297],
["Faculdade Maurício de Nassau", 76],
["Faculdade Messiânica", 653],
["FACULDADE METODISTA DE SANTA MARIA - FAMES", 2151],
["Faculdade Modal", 2391],
["Faculdade Montessoriano de Salvador", 1318],
["Faculdade Nazarena do Brasil", 1089],
["Faculdade Nova Ateneu", 581],
["Faculdade Nova Roma", 660],
["Faculdade Padrão  - Aparecida de Goiânia", 149],
["Faculdade Paraíso", 665],
["Faculdade Paulista São José", 1666],
["Faculdade Pedro II", 852],
["Faculdade Pentágono", 671],
["Faculdade Peruíbe", 672],
["Faculdade Pitágoras", 57],
["Faculdade Porto União", 2814],
["Faculdade Prisma", 1364],
["Faculdade Professor Daltro", 2329],
["Faculdade QI", 187],
["Faculdade Raimundo Marinho", 119],
["Faculdade Santa Fé", 2063],
["Faculdade Santa Helena", 1654],
["Faculdade Santo André", 2777],
["Faculdade Santo Antônio", 235],
["Faculdade São Francisco de Assis", 1381],
["Faculdade São Judas Tadeu", 1415],
["Faculdade São Miguel", 690],
["Faculdade São Salvador", 1388],
["Faculdade São Tomaz", 2149],
["Faculdade Sequencial", 2044],
["Faculdades FACCAT", 464],
["Faculdades Guarulhos", 699],
["Faculdades IESGO", 1205],
["Faculdades Integradas do Vale do Ribeira", 1390],
["Faculdades Integradas Espírita", 623],
["Faculdades Integradas Silva e Souza", 1407],
["Faculdades Integradas Urubupungá - FIU", 1072],
["Faculdades Integradas Vianna Júnior", 1649],
["Faculdades IPEP", 2],
["Faculdades João Paulo II", 1987],
["Faculdades Kennedy", 1904],
["Faculdades Londrina", 1574],
["Faculdade Sogipa de Educação Física", 227],
["Faculdade Stella Maris", 1432],
["Faculdade Sumaré", 5],
["Faculdade Teológica Ibetel", 2367],
["Faculdade Três Marias", 2325],
["Faculdade Unida de Vitória", 707],
["Faculdade Zumbi dos Palmares", 1652],
["Fadileste", 719],
["FAECE - Faculdade de Ensino e Cultura do Ceará", 1201],
["FAEC - Faculdade Educacional de Colombo", 733],
["FAEC - Faculdade Euclides da Cunha", 2742],
["FAEESP – Faculdade Aliança Educacional do Estado de São Paulo", 2710],
["FAE - Faculdade Anglicana de Erechim", 740],
["FAE -Faculdade das Águas Emendadas", 734],
["FAEME - Faculdade Evangélica do Meio do Norte", 2028],
["FAEPI - Faculdade Evangélica do Piauí", 737],
["FAESF - Faculdade de Educação São Francisco", 743],
["FAESP - Faculdade Evangélica de São Paulo", 1996],
["FAESPI", 747],
["FAETI - Faculdade de Educação e Tecnologia Iracema", 2749],
["FAF - Faculdade do Futuro", 620],
["FAFIBE - Faculdade de Filosofia, Ciências e Letras de Boa Esperança", 752],
["FAFICA", 1010],
["FAFIG - Faculdade de Foz do Iguaçu", 2126],
["FAFIRE", 758],
["FAFOR - Faculdade de Fortaleza", 1657],
["FAGV - Faculdade de Administração de Governador Valadares", 766],
["FAI - Faculdade de Iporá", 613],
["FAINAM - Faculdade Interação Americana", 773],
["FAINOR - Faculdade Independente do Nordeste", 775],
["FAINSEP - Faculdade Instituto Superior de Educação do Paraná", 1231],
["FAISP - Faculdade Interativa de São Paulo", 2753],
["FAITA - Faculdade Itanhaém", 782],
["FAJOLCA - Faculdade de Ipojuca", 787],
["FAJOPA - Faculdade João Paulo II", 789],
["FAK - Faculdade Kurios", 1934],
["FALEC", 790],
["FAM", 74],
["FAMA - Faculdade da Amazônia", 502],
["FAMA - Faculdade de Tecnologia Machado de Assis", 1395],
["FAMA - Faculdade Metropolitana de Anápolis", 626],
["FAMAP", 502],
["FAMAQUI - Faculdade Mário Quintana", 1953],
["FAMART - Faculdade Martins", 2348],
["FAMATH - Faculdades Integradas Maria Thereza", 809],
["FAMEPLAN", 816],
["FAMESP - Faculdade Método de São Paulo", 22],
["FAMETRO - Faculdade Metroplitana de Manaus", 821],
["FAMEV - Faculdade Metropolitana do Vale do Aço", 2249],
["FAMIG - Faculdade Minas Gerais", 824],
["FAMOSP - Faculdade Mozarteum de São Paulo", 1321],
["FANEB - Faculdade do Nordeste da Bahia", 832],
["FANEC - Faculdade Natalense de Ensino e Cultura", 2142],
["FANEESP- Faculdade Nacional de Educação e Ensino", 833],
["FANORTE", 1989],
["FAPAL - Faculdade de Palmas", 2129],
["FAPAM - Faculdade de Pará de Minas", 843],
["FAPAN - Faculdade Pan Amazônica", 1568],
["FAPAR-Faculdade Paranaense", 2138],
["FAPEC", 1678],
["FAPEN - Faculdade Paraense de Ensino", 2130],
["FAP - Faculdade de Piracanjuba", 855],
["FAP - Faculdade Paraibana", 2143],
["FAP - Faculdade Paraíso", 665],
["FAPI - Faculdade de Pinhais", 222],
["FAPI - Faculdade do Piauí", 1907],
["FAPS - Faculdade de Tecnologia Porto Sul", 1727],
["FAPSS - São Caetano do Sul", 2015],
["FAREC - Faculdade do Recife", 2127],
["FAR - Faculdade Adelmar Rosado", 1350],
["FARJ - Faculdade Regional Riachão do Jacuípe", 862],
["FAROL - Faculdade de Rolim de Moura", 865],
["FASB - Faculdade do Sul da Bahia", 1021],
["FASC - Faculdade de Santa Catarina", 682],
["FASEH - Faculdade da Saúde e Ecologia Humana", 880],
["FASER – Faculdade Sergipana", 209],
["FASERRA", 883],
["FASES - Faculdade Shalom de Ensino Superior", 1761],
["FASF - Faculdade Sul Fluminense", 887],
["FASFI - Faculdade São Fidélis", 684],
["FASI – Faculdade de Saúde de Ibituruna", 888],
["FASNE - Faculdade Salesiana do Nordeste", 891],
["FASS - Faculdade São Sebastião", 894],
["FASUP - Faculdade de saúde de Paulista", 1246],
["FASVIPA - Faculdade São Vicente", 899],
["FATECE - Faculdade de Tecnologia, Ciências e Educação", 910],
["FATECIE", 900],
["FATECI - Faculdade de Tecnologia Intensiva", 140],
["FATEC PE - Faculdade de Tecnologia e Ciências", 916],
["FATEC PR - Faculdade de Tecnologia de Curitiba", 0],
["FATEC - RO", 907],
["FATEJ - Faculdade de Tecnologia Jardim", 920],
["FATEPA", 900],
["FATESA - Faculdade de Tecnologia em Saúde", 1807],
["FATIN - Faculdade de Teologia Integrada", 934],
["FAUSB", 1490],
["FAVENI", 941],
["FAVI - Instituto de Ensino Superior", 2147],
["FAZAG", 946],
["FAZU - Faculdades Associadas de Uberaba", 917],
["FBB - Faculdade Batista Brasileira", 948],
["FBBR - Faculdade Batista Brasileira do Recôncavo", 2176],
["FBC - Faculdade Brasil Central", 949],
["FCGB - Faculdade de Ciências Gerenciais da Bahia", 1498],
["FCG - Faculdade Campo Grande", 1186],
["FCG - Faculdade de Ciências Educacionais Capim Grosso", 1923],
["FCV - Faculdade Cidade Verde", 968],
["FDCON - Faculdade de Direito de Contagem", 971],
["FEAD", 145],
["FEICS", 992],
["FEITEP – Faculdade de Engenharia", 993],
["FEPAM - Faculddae Europeia de Administração de Marketing", 629],
["FERA - Faculdade de Ensino Regional Alternativa", 1991],
["FESAM - Faculdade de Ensino Superior da Amazônia", 2041],
["FEUDUC - Fundação Educacional de Duque de Caxias", 1020],
["FFCL-Faculdade de Filosofia, Ciências e Letras de Ituverava", 995],
["FG - Faculdade dos Guararapes", 1513],
["FGF - Faculdade Integrada da Grande Fortaleza", 1025],
["FIA", 1032],
["FIAVEC", 1280],
["FIBH - Faculdade Iseib de Belo Horizonte", 1945],
["FICEPE", 2198],
["FIC - Faculdades Integradas de Cuiabá", 151],
["FIED – Faculdade Ieducare", 2049],
["FIEL -  Faculdades Integradas Einstein de Limeira", 78],
["FIJ - Faculdades Integradas de Jacarepaguá", 1052],
["FIMCA", 1054],
["FIPA - Faculdades Integradas Padre Albino", 1058],
["FIP - MOC Faculdades Integradas Pitágoras", 1061],
["FISBE - Faculdade ISEIB de Betim", 1946],
["FISE - Faculdades Integradas de Sergipe", 1790],
["FISO - Faculdades Integradas Soares de Oliveira", 1418],
["FJF - Faculdade Juiz de Fora", 1667],
["FJN - Faculdade de Juazeiro do Norte", 1075],
["FLATED", 1077],
["FMT - Faculdade Madre Thaís", 650],
["FMU - Faculdades Metropolitanas Unidas", 29],
["FNG - Faculdade do Norte Goiano", 544],
["FOCCA - Faculdade de Olinda", 1091],
["FPG - Faculdade Pinheiro Guimarães", 674],
["FRJ- FACULDADE REGIONAL JAGUARIBANA", 2774],
["FTC - Faculdade de Tecnologia e Ciências", 99],
["FTP - Faculdade de Tecnologia de Palmas", 2038],
["FUCAP -  Faculdade Capivari", 1135],
["FUNORTE", 1156],
["FUNVIC", 856],
["Grupo Educacional HOTEC", 1169],
["IBES", 1964],
["IBHES - Instituto Belo Horizonte de Ensino Superior", 1177],
["IBRATE", 1777],
["IBTA - Instituto Brasileiro de Tecnologia Avançada", 40],
["ICEC - Instituto Cuiabá de Ensino e Cultura", 2140],
["ICESPI - Instituto Católico de Estudos Superiores do Piauí", 2013],
["ICSH - CESB", 1187],
["IESACRE", 1914],
["IESA - Instituto de Ensino Superior de Alagoas", 2123],
["IESCAMP - Instituto de Educação e Ensino Superior de Campinas", 1202],
["IESF - Faculdade São Francisco", 1204],
["IESGF - Instituto de Ensino Superior da Grande Florianópolis", 2128],
["IESI - Instituto de Educação Superior de Ituberá", 0],
["IESI- Instituto de Ensino Superior de Itapira", 23],
["IESMT - Instituto de Ensino Superior de Mato Grosso", 2136],
["IESO-Instituto de Ensino Superior de Olinda", 2145],
["IESP - Instituto de Ensino Superior de Piedade", 851],
["IESPLAN - Faculdade Planalto", 112],
["IESRN - Instituto de Ensino Superior do Rio Grande do Norte", 2141],
["IFITEG - Instituto de Filosofia e Teologia de Goiás", 1214],
["IIES- Instituto Itapetiningano de Ensino Superior", 2144],
["IMEC - Instituto Maranhense de Ensino e Cultura", 2122],
["INEC - Faculdade de Educação Acriana Euclides da Cunha", 1992],
["INESA - Instituto de Ensino Superior Santo Antônio", 1222],
["Instituto Educar", 2763],
["IPESU - Instituto Pernambucano de Ensino Superior", 2137],
["ISCA Faculdades", 1254],
["ISEB - Instituto Superior de Educação de Barretos", 1255],
["ISEPRO - Instituto Superior de Educação Programus", 1261],
["ITES- Instituto Taubaté de Ensino Superior", 1275],
["Newton Paiva", 1326],
["Nova Faculdade", 2091],
["Rede de Ensino Doctum", 89],
["Rede de Ensino JK", 123],
["SINAL - Faculdade de Teologia e Filosofia", 1409],
["SOBE - Sociedade Brasileira de Educação", 2678],
["SPEI", 1430],
["UBM - Centro Universitário de Barra Mansa", 1442],
["UCAM - Universidade Candido Mendes", 1443],
["UCB - Universidade Castelo Branco", 301],
["UDF - Centro Universitário do Distrito Federal", 1454],
["UNAMA - Universidade da Amazônia", 1462],
["UNEOURO – Faculdade de Ouro Preto do Oeste", 200],
["UNESC - Centro Universitário do Espírito Santo", 1471],
["UNESC Faculdades", 0],
["UNIABEU", 1477],
["UNIASSELVI", 163],
["UNIBAHIA", 204],
["UNIBRATEC", 1488],
["UNICARIOCA", 1495],
["UNICE", 205],
["UNIC Educacional", 1895],
["UNICEP", 1500],
["UNICESUMAR", 348],
["UNICID", 30],
["UNICRISTÃ", 2340],
["UNIEST", 2054],
["UNIFACS", 52],
["UNIFAMMA", 1530],
["UNIFEOB", 1536],
["UNIFIA - Centro Universitário Amparense", 1538],
["UNIFIEO", 36],
["UNIFOR - Universidade de Fortaleza", 1542],
["UNIFOZ - Faculdade de Foz do Iguaçu", 2126],
["UNIFRAN", 67],
["UNIGUAÇU / FAESI", 1549],
["UNIJORGE", 17],
["UNILAGO – União das Faculdades dos Grandes Lagos", 1555],
["UNILINS", 1563],
["UninCor", 1572],
["UNINORTE", 1914],
["UNIPAC", 85],
["UniPaulistana", 1591],
["UNIPLAN - Centro Universitário Planalto do Distrito Federal", 1596],
["UNIP - UNIVERSIDADE PAULISTA", 25],
["UniSant'Anna", 37],
["UNISA - Universidade de Santo Amaro", 1601],
["UNISUL", 1611],
["UNIVERITAS", 2372],
["Universidade Braz Cubas", 46],
["Universidade Cruzeiro do Sul", 27],
["Universidade Positivo", 1639],
["UNIVÉRTIX - Faculdade Vértice", 712],
["UNOESTE - UNIVERSIDADE DO OESTE PAULISTA", 66],
["UNP – Universidade Potiguar", 1638],
["UNP - Universidade Potiguar EAD", 1638],
["UPIS", 1641],
["URI", 1365],
["UVA-Universidade Veiga de Almeida", 55],
["Faculdade Adjetivo - CETEP", 250],
["FATEBE - Faculdade Teológica Betânia", 1851],
["UNOPAR", 61]]

confirmed |> Enum.each( fn([name,id]) ->
  a = (from p in PpaUniversitiesAssociation, where: p.cr_university_name == ^name, select: count("*")) |> Repo.one

  if a == 0 do
    association = %PpaUniversitiesAssociation{cr_university_name: name, qb_university_id: id}
    Repo.insert association
  end
end )
